language: node_js
node_js: 
  - "12.16.3"

services:
  - mongodb

install:
  - yarn install

env:
  global:
    - NODE_ENV=test
    - TEST_MONGODB_URI=mongodb://localhost:27017/test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sleep 15
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - yarn test:coverage

cache:
    npm: false
    yarn: false

after_success:
  - ./cc-test-reporter after-build
